---
title: "Ukraina Covid"
author: "Sławomir Matuszak"
date: "28 03 2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r include=FALSE, message=FALSE}
library(maptools)
library(rgeos)
library(rgdal)
library(ggplot2)
library(gridExtra)
library(reshape2)
library(ggthemes)
library(scales)
library(tidyr)
library(dplyr)
```
```{r message=FALSE, include=FALSE}
shp1 <- readOGR("E:/R/UA_spis/data/mapa", layer = "obwod_pl")
#zmieniamy format danych
shp1f <- fortify(shp1, region = "ADM1_PCODE")


# dzienne dane z obwodów i szpitali
load(file = "E:/R/COVID-19/Ukraina.dane/obwody.lista.Rda")
obwody.lista <- obwody %>%
  # trzeba poprawic współrzędne Kijowa, bo nie widać go na mapie
  select(1:3,7)
obwody.lista[13,1] <- 50.777435
obwody.lista[13,2] <- 30.167475
rm(obwody)

load(file = "E:/R/COVID-19/Ukraina.dane/obwody_dzienne.Rda")
obwody <- obwody %>%
  select(-c(7,8))%>%
  left_join(obwody.lista, by="Kod")%>%
  mutate(lat = as.numeric(lat), long = as.numeric(long))

load(file = "E:/R/COVID-19/Ukraina.dane/szpitale.lozka.Rda")
szpitale.lozka <- szpitale.lozka %>% 
  select(-c(6,7))%>%
  left_join(obwody.lista, by="Kod")%>%
  mutate(lat = as.numeric(lat), long = as.numeric(long))

load(file = "E:/R/COVID-19/Ukraina.dane/szpitale.oblozenie.Rda")
szpitale.oblozenie <- szpitale.oblozenie %>%
  select(-c(3,4))%>%
  left_join(obwody.lista, by="Kod")%>%
  mutate(lat = as.numeric(lat), long = as.numeric(long))

```

```{r}
a <- obwody %>%
  filter(data== max(data)) %>%
  group_by(Obwód, Kod, data)%>%
  summarise(
    liczba = sum(liczba),
    data2 = max(data)+1
  )

ggplot() + 
  geom_map(data=a, aes(map_id=Kod, fill=liczba), map=shp1f) + 
  geom_path(data = shp1f, aes(x=long, y=lat, group=group), colour="grey", size=0.001) + 
  coord_map(projection = "mercator") + 
  scale_fill_gradient(low = "white", high = "orange") +
  labs(fill= "liczba \nzarażeń", title = "Liczba potwierdzonych przypadków Covid-19",
       subtitle =  paste( "stan na", format(as.Date(a$data2), "%d/%m/%Y"))) +
  geom_label(data=szpitale.lozka, aes(x=long, y=lat), label=a$liczba) +
  theme_bw()+
  theme(axis.ticks = element_blank(), panel.border = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(), legend.position = c(0.1, 0.2),
        panel.grid.minor = element_blank(),panel.grid.major = element_blank(), plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```


***


```{r}
a <- obwody %>%
  filter(data== max(data)) %>%
  filter(skumulowane == "zgony") %>%
  group_by(Obwód, Kod, data)%>%
  summarise(
    liczba = sum(liczba),
    data2 = max(data)+1
  )

ggplot() + 
  geom_map(data=a, aes(map_id=Kod, fill=liczba), map=shp1f) + 
  geom_path(data = shp1f, aes(x=long, y=lat, group=group), colour="grey", size=0.001) + 
  coord_map(projection = "mercator") + 
  scale_fill_gradient(low = "white", high = "red") +
  labs(fill= "liczba \nzgonów", title = "Liczba zgonów z powodu Covid-19",
       subtitle =  paste( "stan na", format(as.Date(a$data2), "%d/%m/%Y")),
       caption = "Źródło - Ministerstwo Zdrowia Ukrainy") +
  geom_label(data=szpitale.lozka, aes(x=long, y=lat), label=a$liczba) +
  theme_bw()+
  theme(axis.ticks = element_blank(), panel.border = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(), legend.position = c(0.1, 0.2),
        panel.grid.minor = element_blank(),panel.grid.major = element_blank(), plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```


***


```{r}
a <- obwody %>%
  filter(data== max(data)) %>%
  group_by(Obwód, Kod, data)%>%
  summarise(
    ilosc = sum(ilosc),
    data2 = max(data)+1
  )
suma <- sum(a$ilosc)

b <- arrange(a,  desc(ilosc))
```

W ciągu minionej doby zarejestrowano `r suma` nowych przypadków, najwięcej `r if_else(b[1,1]=="Kijów", paste("w Kijowie"), paste0("w obwodzie ", b[1,1], "m"))` (`r b[1,4]`), `r if_else(b[2,1]=="Kijów", paste("w Kijowie"), paste0("w obwodzie ", b[2,1], "m"))` (`r b[2,4]`) oraz `r if_else(b[3,1]=="Kijów", paste("w Kijowie"), paste0("w obwodzie ", b[3,1], "m"))` (`r b[3,4]`). 

```{r include=FALSE}
if_else(b[1,1]=="Kijów", paste("w Kijowie"), paste0("w obwodzie ", b[1,1], "m"))
```


```{r}

ggplot() + 
  geom_map(data=a, aes(map_id=Kod, fill=ilosc), map=shp1f) + 
  geom_path(data = shp1f, aes(x=long, y=lat, group=group), colour="grey", size=0.001) + 
  coord_map(projection = "mercator") + 
  scale_fill_gradient(low = "white", high = "orange") +
  labs(fill= "liczba nowych\nprzypadków", title = "Liczba nowych przypadków Covid-19 w ciągu ostatniej doby",
       subtitle =  paste( "stan na", format(as.Date(a$data2), "%d/%m/%Y")),
       caption = "Źródło - Ministerstwo Zdrowia Ukrainy") +
  geom_label(data=szpitale.lozka, aes(x=long, y=lat), label=a$ilosc) +
  theme_bw()+
  theme(axis.ticks = element_blank(), panel.border = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(), legend.position = c(0.1, 0.2),
        panel.grid.minor = element_blank(),panel.grid.major = element_blank(), plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```

```{r}
a <- obwody %>%
  filter(data== max(data)) %>%
  group_by(Obwód, Kod, data, population)%>%
  summarise(
    liczba = sum(liczba),
    data2 = max(data)+1
  ) %>%
  mutate(zach.100 = liczba*100000/population)%>%
  mutate(zach.100 = round(zach.100, 2))

ggplot() + 
  geom_map(data=a, aes(map_id=Kod, fill=zach.100), map=shp1f) + 
  geom_path(data = shp1f, aes(x=long, y=lat, group=group), colour="grey", size=0.001) + 
  coord_map(projection = "mercator") + 
  scale_fill_gradient(low = "white", high = "orange") +
  labs(fill= "liczba\nzarażonych", 
       title = "Liczba zarażonych Covid-19 na 100 tys. mieszkańców",
       subtitle =  paste( "stan na", format(as.Date(a$data2), "%d/%m/%Y")),
       caption = "Źródło - Ministerstwo Zdrowia Ukrainy, liczba ludności wg tzw. spisu Dubileta") +
  geom_label(data=szpitale.lozka, aes(x=long, y=lat), label=a$zach.100) +
  theme_bw()+
  theme(axis.ticks = element_blank(), panel.border = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_blank(), legend.position = c(0.1, 0.2),
        panel.grid.minor = element_blank(),panel.grid.major = element_blank(), plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
```


```{r}
colors <- c("podejrzewani"="orange", "chorzy"="red", "wolne łóżka"="blue")
ggplot(data=szpitale.oblozenie)+
  geom_bar(aes(x=reorder(Obwód, -liczba), y=liczba, fill=stan), stat="identity")+
  labs(x="obwód", y="liczba łóżek", fill="",
       title = "Sytuacja w szpitalach na Ukrainie",
       subtitle = "wg stanu na 28 marca",
       caption = "Źródło: Departament Polityki Regionalnej i Decentralizacji Biura Prezydenta Ukrainy.")+
  scale_fill_manual(values = colors)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1), plot.title = element_text(hjust = 0.5), 
        plot.subtitle = element_text(hjust = 0.5) , legend.direction = "horizontal", legend.position=c(0.76,0.9), plot.caption = element_text(hjust = 0, size = 8))

```

